import "Windows.Media.idl";

#include <sdkddkver.h>

namespace VideoCaptureTransform
{
	[version(NTDDI_WIN8), activatable(NTDDI_WIN8)]
	runtimeclass CaptureEffect
	{
		[default] interface Windows.Media.IMediaExtension;
	}
}